version: '3.9'

services:
  web:
    build: ..  # Build the image from the current directory
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000
    depends_on:
      - redis
      - mongo  # Add dependency on the mongo service
    environment:
      REDIS_URL: redis://redis:6379  # Set environment variable for Redis connection
      MONGO_URL: mongodb://mongo:27017/test  # Set environment variable for MongoDB connection

  redis:
    image: "redis:latest"  # Use the official Redis image
    ports:
      - "6379:6379"  # Expose Redis container port 6379 to host port 6379

  mongo:
    image: "mongo:latest"  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB container port 27017 to host port 27017 (default)
    volumes:
      - mongo-data:/data/db  # Optional volume to persist MongoDB data
volumes:
  mongo-data: