version: "3.8"  # Replace with your Docker Compose version

services:
  redis:
    build: ./redis  # Path to your Redis docker-compose.yml
    ports:
      - "6379:6379"  # Map container port 6379 to host port 6379

  fastapi:
    build: .  # Build from the current directory (./)
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    depends_on:
      - redis  # Ensure Redis service starts before the FastAPI service
